# Project.toml
[deps]
# Core Data Science
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"      # Jupyter kernel
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"  # Data manipulation
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"         # File I/O
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"       # Apache Arrow format
Parquet = "626c502c-15b0-58ad-a749-f091afb673ae"     # Parquet file support

# Statistics and Machine Learning
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"  # Basic statistics
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"   # Advanced statistics
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"         # Machine learning
XGBoost = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"     # Gradient boosting
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"  # Clustering algorithms
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"         # Generalized Linear Models
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"  # PCA, etc.

# Visualization
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"       # General plotting
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"  # Statistical plotting
VegaLite = "112f6b84-f20a-5717-9410-f14c3385d7d6"    # Declarative vis

# Data Manipulation and Pipeline Tools
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"  # DataFrame operations
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"           # Pipeline operations
TableTransforms = "0d432bfd-3ee1-4ac1-886a-39f05cc69a3e"  # Data transformations

# Utility and Helper Packages
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"       # JSON handling
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"        # YAML support
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"  # Additional data structures
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"       # Date/time operations

[compat]
julia = "1.9"
DataFrames = "1.6"
CSV = "0.10"
Plots = "1.39"
MLJ = "0.20"
XGBoost = "2.5"
StatsBase = "0.34"